### ISSUE TITLE
Wrong result in simple damage calculation

### ISSUE THREAD

**Issue by max9111** [boschresearch/pylife#21]
I tried to calculate the damage for a simple synthetical signal, where damage calculation can be verified manually.
Did I make a mistake in using PyLife or is there a Bug?

**Pylife example**

```python:
import pylife.stress.timesignal as ts
import pylife.stress.rainflow as RF
import pylife.stress.rainflow.recorders as RFR

woehler_curve = pd.Series({
    'SD':  1000.,
    'ND':  1e7,
    'k_1': 5,
})

data_calc = np.sin(np.linspace(0,2_000*np.pi,200_000))*1_000 + np.sin(np.linspace(0,1_000*np.pi,200_000))*1_000

#Rainflow counting
rainflow_bins = 64
recorder   = RFR.FullRecorder()
detector   = RF.FKMDetector(recorder=recorder).process(data_calc)
rf_series  = detector.recorder.histogram(rainflow_bins)

#Damage calculation
damage_miner_elementary = woehler_curve.fatigue.miner_elementary().damage(rf_series.load_collective)

print(damage_miner_elementary .sum())
#0.0005812095296612522
# -> Manual calculation: 0.0008451272205597859
```

**Calculating the damage manually**

There are 500 cycles with an ampiltude of 369.00016409606667 and 500 cycles with an amplitude of 1760.172592660727.

```python:
k=5
SD=1000
ND=1e7
LW=500

damage = LW/(ND*(1760.1725926607273/SD)**(-k)) + LW/(ND*(369.00016409606667/SD)**(-k))
print(damage)
#0.0008451272205597859
```

**Comment by DKreuter** [comment]
Hi @max9111, if you close the residuals (e.g. by adding one more cycle:
```
lc_df[lc_df.shape[0] + 1] = lc_df.max()
lc_df[lc_df.shape[0] + 2]  = lc_df.min()
```
), you will get the expected cycles and the damage results, too:
`rainflow_bins = 1024
recorder   = RFR.FullRecorder()
detector   = RF.FKMDetector(recorder=recorder).process(lc_df)
rf_series  = detector.recorder.histogram(rainflow_bins).load_collective
rf_series.cycles[rf_series.cycles>0]`

and than 
`damage_miner_elementary = woehler_curve.fatigue.miner_elementary().damage(rf_series)`

To check the residuals:
`detector.residuals`

**Comment by johannes-mueller** [comment]
Closing this issue in favor of the discussion thread #22.

**Comment by johannes-mueller** [comment]
Closing this issue in favor of the discussion thread #22
