### ISSUE TITLE
Loosen version constraints for numpy (currently ==1.23.5)

### ISSUE THREAD

**Issue by j-riebe** [boschresearch/pylife#40]
# Issue
I recently encountered version conflicts between `pylife` and other packages due to the pinned numpy version.

Is there a reason why the numpy is pinned to `==1.23.5`?
If not, is it be possible to loosen the version constraints so that more recent numpy versions are supported?

The test suite passes with all python/numpy combinations (except python3.8 which is only supported for `numpy<1.25`)

| Python \| numpy   | 1.24  | 1.25 | 1.26 |
|--------------------|------|------|------|
| 3.8                        |   ✔️ | not supported | not supported |
| 3.9                        |   ✔️ | ✔️   | ✔️   |
| 3.10                      |  ✔️  | ✔️   | ✔️   |
| 3.11                      | ✔️   | ✔️   | ✔️   | 

_BTW: version 1.23 will each its [end of life](https://endoflife.date/numpy) by 24 Jun 2024._

**Comment by johannes-mueller** [comment]
Thanks for reaching out.

We are actually watching this in #39. Maybe the numba issues have been resolved in the meantime so that we can do a release with an uplifted dependency.

**Comment by johannes-mueller** [comment]
Fixed in #39
