### ISSUE TITLE
Reevaluate positional parameters and tupled returns

### ISSUE THREAD

**Issue by johannes-mueller** [boschresearch/pylife#51]
There are some positional parameters and tupled returns in `src/pylife/stress/rainflow/fkm_nonlinear.py` which we should consider changing for readability.

**Comment by maierbn** [comment]
I made most positional parameters keyword parameters.

Concerning the tupled returns, I hope it's not so much of a problem. There are only two methods that return tuples of the form `return current_point, iz, ir`. It's not possible to split the functions into three without code duplication or much effort.
