### ISSUE TITLE
Doubly linked demo notebooks in the docs

### ISSUE THREAD

**Issue by johannes-mueller** [boschresearch/pylife#53]
There are a couple of fkm related demo notebooks that are linked in `tutorials.rst` as well as in `cookbook.rst`. This leads to confusion as Sphinx recognizes them as the same file. Then when clicking on one of it from the Cookbook page you are taken to the Tutorial page.

We should think which we link from where.

**Comment by johannes-mueller** [comment]
Also [this](https://github.com/boschresearch/pylife/blob/ae9f4439b6e780b7cae8bacdd35a77c83bd78166/docs/cookbook.rst?plain=1#L22) reference does not work. I wonder, if it is actually needed because as of now, in the tutorials there is no fkm-nl related stuff which is not in the cookbook.

**Comment by maierbn** [comment]
Yes, it's not needed, originally I had some tutorials there but without much extra contents.

**Comment by maierbn** [comment]
Addressed in #59
