### ISSUE TITLE
odbclient: Proper error message on unsupported elements

### ISSUE THREAD

**Issue by johannes-mueller** [boschresearch/pylife#64]
We need proper error messages for the scenario shown here https://github.com/boschresearch/pylife/discussions/58#discussioncomment-8053604 i.e. `odbclient` hits unsupported elements and can't broadcast the stress tensor.

**Comment by MaximLutovinov** [comment]
Hello Johannes,

here are two odb-files. The first one ("test-shell-solid-beam_elems") contain solid, shells, beam, and kinematic coupling elements. The second one ("model_w_conn3d2") is the same, but with an addition of a conn3d2 element. If possible, please test both. 

[test-shell-solid-beam_elems.zip](https://github.com/boschresearch/pylife/files/13938439/test-shell-solid-beam_elems.zip)
[model_w_conn3d2.zip](https://github.com/boschresearch/pylife/files/13938460/model_w_conn3d2.zip)
