### ISSUE TITLE
Drop matplotlib dependency

### ISSUE THREAD

**Issue by johannes-mueller** [boschresearch/pylife#91]
We have a dependency to matplotlib because in for the time signal handling we use `matplotlib.mlab.psd`. That function calculates the power spectral density. There is a [functionality in scipy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.periodogram.html) which claims to do the same thing.

## Task

Check if we can replace `matplotlib.mlab.psd` with the `scipy.signal.periodogram` and thus drop the dependency to matplotlib.

**Comment by DKreuter** [comment]
@johannes-mueller :  The psd functionality is replaced by scipy.signal.welch. In the setup.config file matplotlib is still defined as a required package, Should I remove it or is it needed anywhere else?

**Comment by johannes-mueller** [comment]
It's still used [here](https://github.com/boschresearch/pylife/blob/develop/src/pylife/stress/timesignal.py#L222). Can we replace that one also?
